### PR TITLE
Add client and server example

### PR DESCRIPTION
**Pull request by Alexey2257**
Hi! I am thrilled to have an async job processor, and I think many could benefit from it, so I wanted to try this one. I see there is an `async-job-adapter-active_job` and an example for Rails; however, I prefer not using extra dependencies. I found `client.rb `and `server.rb` files in the root that probably should be examples of a simple client and server, but they crashed with exceptions. I think that's because they were written before some significant code changes. After some time, I came up with a working solution, but I'm not sure if it's the right way. It is also possible to modify Generic to schedule jobs as well, like `ExampleJob.perform_async`, but I think it will make this example more complicated. What do you think?

## Types of Changes

- Maintenance.

## Contribution

- [x] I tested my changes locally.
- [x] I agree to the [Developer's Certificate of Origin 1.1](https://developercertificate.org/).

### CODE REVIEW

**Comment by ioquatix** [comment]
My initial thoughts:

I understand the desire to provide a "full implementation" however I do want a base class which is fully generic.

Please give me some time to think about what is the best approach.

**Comment by Alexey2257** [comment]
I can leave Generic class as it was and create a new base class in the examples directory, so it will be used just as example of implementation.

**Comment by ioquatix** [comment]
That would be a reasonable starting point.

**Comment by Alexey2257** [comment]
Done, now gem's code is untouched, only examples added. Maybe in the future we could extract "full implementation" in a separate gem so that one could use `async-job` with something like `async-job-executor` instead of `async-job-adapter-active_job`.

**Comment by ioquatix** [comment]
Your proposed option of having a separate job framework like `async-job-executor` is a reasonable option, however I also understand the value of your original proposal. I have not had time to review the code in detail and think about what makes the most sense. Both options are reasonable, but a separate gem is a little more complex for users.

**Pull request merged**
